### ISSUE TITLE
UpdatePathOnRename does not work on .tsx files but works on .ts files

### ISSUE THREAD

**Issue by anark** [neoclide/coc-tsserver#52] opened 2019-07-30 15:30 UTC
It appears that by default watchman from this plugin will only watch .ts files and not .tsx files.

I think it has to do with https://github.com/neoclide/coc-tsserver/blob/1e6153289fb1e556f91ff82c9e3419f57bdffe21/src/server/features/updatePathOnRename.ts#L28 but not sure.

**Comment by chemzqm** [comment] 2019-07-30 16:14
It's the problem, consider send a PR

**Comment by anark** [comment] 2019-07-30 16:49
I have one here https://github.com/neoclide/coc-tsserver/pull/53.

Just having trouble getting my local system setup to test it out locally as I am new to developing on Coc Extensions

**Comment by anark** [comment] 2019-08-01 05:14
Unfortunately this fix didn't work and now neither file type is passed triggers the change.  I've tried all sorts of different changes to the glob but can't get it to run with an optional x for tsx.  Any idea why the glob of '**/*.{ts,tsx}' doesn't work but '**/*.ts' or '**/*.tsx' will work.

I cannot find a way to make the watcher respect the glob for both .ts and .tsx.

**Comment by chemzqm** [comment] 2019-08-01 05:20
This feature needs watchman to work, you can checkout output from watchman https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by anark** [comment] 2019-08-01 05:33
I have watchman and the output shows that it subscribes, however when a file is moved it doesn't rename the file and nothing is registered in the output channel.

It works fine when I use a glob of '**/*.tsx' however then this would not work for .ts files and only for  .tsx files

**Comment by chemzqm** [comment] 2019-08-01 06:07
Bug of glob pattern with watchman, fixed on coc.nvim master.

**Comment by anark** [comment] 2019-08-01 14:32
Awesome!  Thank you so much for your help!

**Comment by anark** [comment] 2019-08-02 15:23
With the update to Coc this is now working when you move either a .ts or .tsx file.

It does not work if you rename a folder containing these file types so you have to be careful to rename/move files one by one.

**Comment by chemzqm** [comment] 2019-08-02 15:34
@anark does VSCode support folder rename? If it does, I think we can add it too.

**Comment by anark** [comment] 2019-08-03 19:00
Yes,
VSCode does update paths when you rename a folder.  How can we do this in Coc?

**Comment by anark** [comment] 2020-02-03 00:26
This feature UpdateOnRename is no longer working for me while using watchman ect.  Is this working for anyone else?

**Comment by kristenmills** [comment] 2020-02-04 20:39
UpdatePathOnRename isn't working for me at all right now as well.

**Comment by qisaw** [comment] 2020-02-11 20:21
Same here. UpdatePathOnRename is not working for any types of files for me either

**Comment by chemzqm** [comment] 2020-02-14 16:11
This feature requires [watchman](https://facebook.github.io/watchman/) installed in your \$PATH.

**Comment by anark** [comment] 2020-02-14 20:29
Watchman is installed, and running but doesn't work.  Output from CocConfig shows that it is being watched but this feature no longer works

**Comment by adc17** [comment] 2020-04-09 21:45
Just a +1 that import paths are not being updated on file rename for me right now. I have watchman installed and get pretty much the same output as @anark when I view its output. Any advice on other ways that I could help you debug?

**Comment by brentmitchell25** [comment] 2020-04-14 18:08
I am also not getting files renamed on import, however I only noticed it in subdirectories. If I change a `*.ts` file in the root then watchman is triggerd and the file is renamed. If I have a file at `src/*.ts` or any other subdirectories then watchman does not trigger.

**Comment by adc17** [comment] 2020-04-15 02:10
Good spot! I'm seeing the same behaviour.

**Comment by pablopunk** [comment] 2020-04-16 10:17
I believe watchman is actually watching all files and then filtering out using the glob pattern?

https://github.com/neoclide/coc.nvim/blob/70ed90155cfd6caf153011155e1d741b3ec433dc/src/watchman.ts#L104

Maybe the issue is there?

**Comment by chemzqm** [comment] 2020-04-18 08:54
> . If I have a file at src/*.ts or any other subdirectories then watchman does not trigger.

Reproduced.

**Comment by chemzqm** [comment] 2020-04-18 09:24
Introduced by https://github.com/neoclide/coc.nvim/commit/3ab4157c5379795ba5a5542996c46236e42d922d

**Comment by chemzqm** [comment] 2020-04-18 11:20
Latest coc.nvim with coc-tsserver add support for rename on folder name change.

**Closed** 2020-04-18 11:20 UTC
Labels: enhancement

**Comment by muhammad-bin-zafar** [comment] 2022-04-21 04:55
So, is it possible to rename `... helpers/index.ts` to `... utils/index.ts`? If not, does coc-tsserver have a way to rename the directory of a file and have all imported paths updated?
