### ISSUE TITLE
Snippet expansion error then neovim segfault

### ISSUE THREAD

**Issue by pappasam** [neoclide/coc-tsserver#216] opened 2020-10-23 16:14 UTC
Problem: snippet expansion on typescriptreact that modifies an import statement on another line causes a Neovim error, followed by a Neovim segfault :fearful: 

Visualization:

![snippet-expansion-segfault](https://user-images.githubusercontent.com/3723671/97027580-ca709280-150f-11eb-929f-7a985aad4a48.gif)

Neovim error: `Error on request (doKeymap): Vim(return):Error invoking 'doKeymap' on channel 4 (coc): ch 4 returned a response with an unknown request id. Ensure the client is properly synchronized`

OS: Ubuntu 20.04

Neovim:

```
NVIM v0.5.0-767-g0f590ae2a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-25142a98-669f-4031-af45-e52ceeff1b4f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

- coc commit: `  * 8ae18f6 2020-10-20 | feat(float): support close on nvim (HEAD -> master, origin/master, origin/HEAD) [Qiming Zhao]`
- coc-tsserver commit: `  * 334a3dd 2020-10-05 | Release 1.5.8 (HEAD -> master, tag: 1.5.8, origin/master, origin/HEAD) [Qiming Zhao]`
- coc-snippets commit: `  * 71b4c13 2020-09-26 | Release 2.2.1 (HEAD -> master, tag: 2.2.1, origin/master, origin/HEAD) [Qiming Zhao]`
- Expansion command: `imap     <silent> <expr> <C-l> coc#expandable() ? "<Plug>(coc-snippets-expand)" : "\<C-y>"`

**Comment by pappasam** [comment] 2020-10-23 16:16
Note: the snippet in question is provided by `coc-tsserver`. I don't have any community snippets from ultisnips, etc installed.

**Comment by pappasam** [comment] 2020-10-23 16:23
Might be an issue for <https://github.com/neoclide/coc-snippets> or for <https://github.com/neovim/neovim> itself, but I'm raising it here since this is where I found it. Thanks in advance for looking into this!

**Comment by chemzqm** [comment] 2020-10-23 16:58
That could happen when nvim that rpcrequest during another one, I can't reproduce your problem, consider provide minimal vimrc

**Comment by pappasam** [comment] 2020-10-23 17:06
My vimrc is pretty complicated, but after seeing the "0" inserted, my hunch is that this is a combination of: `coc-tsserver`, `coc-snippets`, and `coc-pairs` (all of which I use). I'll try narrow it down and provide something more rigorous for you in the coming hours / days.

**Comment by pappasam** [comment] 2020-10-23 17:10
Yep, it's `coc-pairs`-related. When I remove that plugin, the issue goes away

**Comment by pappasam** [comment] 2020-10-23 17:48
Here's a minimal vimrc:

```vim
" General: packages {{{

" Note: vim-packager automatically executes UpdateRemotePlugins

function s:pack_init() abort
  packadd vim-packager
  call packager#init()
  call packager#add('git@github.com:kristijanhusak/vim-packager', {'type': 'opt'})

  " Autocompletion And IDE Features:
  call packager#add('git@github.com:neoclide/coc.nvim.git', {'do': 'yarn install --frozen-lockfile'})
  for coc_package in [
        \ 'git@github.com:neoclide/coc-pairs.git',
        \ 'git@github.com:neoclide/coc-snippets.git',
        \ 'git@github.com:neoclide/coc-tsserver.git',
        \ ]
    call packager#add(coc_package, {
          \ 'do': 'yarn install --frozen-lockfile && yarn build',
          \ })
  endfor

endfunction

command!       PackInstall call s:pack_init() | call packager#install()
command! -bang PackUpdate  call s:pack_init() | call packager#update({ 'force_hooks': '<bang>' })
command!       PackClean   call s:pack_init() | call packager#clean()
command!       PackStatus  call s:pack_init() | call packager#status()
command! -bang PU          call s:pack_init() | call packager#clean() | call packager#update({ 'force_hooks': '<bang>' })

" }}}
" General: mappings {{{

imap     <silent> <expr> <C-l> coc#expandable() ? "<Plug>(coc-snippets-expand)" : "\<C-y>"

" }}}
" Package: coc.nvim {{{

let g:coc_snippet_next = '<C-j>'
let g:coc_snippet_prev = '<C-k>'
let g:coc_start_at_startup = 1

function! s:autocmd_custom_coc()
  if !exists("g:did_coc_loaded")
    return
  endif
  augroup custom_coc
    autocmd CursorHold * silent call CocActionAsync('highlight')
    autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
  augroup end
endfunction

augroup custom_coc
  autocmd!
  autocmd VimEnter * call s:autocmd_custom_coc()
augroup end

" }}}
" General: options {{{

" Enable filetype detection, plugin loading, and indentation loading
filetype plugin indent on

" Code Completion:
set completeopt=menuone,longest
set wildmode=longest,list,full
set wildmenu

" Messages:
" c = don't give |ins-completion-menu| messages; they're noisy
" I = ignore startup message
set shortmess+=c
set shortmess+=I

" Hidden Buffer: enable instead of having to write each buffer
set hidden

" Sign Column: always show it
set signcolumn=yes

" Mouse: enable GUI mouse support in all modes
set mouse=a

" SwapFiles: prevent their creation
set noswapfile

" Command Line Height: higher for display for messages
set cmdheight=2

" Line Wrapping: do not wrap lines by default
set nowrap

" Indentation:
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=8

" Filename: for gf (@-@='@', see: https://stackoverflow.com/a/45244758)
set isfname+=@-@
set isfname+=:

" Highlight Search: do that
" note: hlsearcha nd nohlsearch are defined in autocmd outside function
set incsearch
set inccommand=nosplit

" Spell Checking:
set dictionary=$HOME/.american-english-with-propcase.txt
set spelllang=en_us

" Single Space After Punctuation: useful when doing :%j (the opposite of gq)
set nojoinspaces

set showtabline=2

set autoread

set grepprg=rg\ --vimgrep

" Paste: this is actually typed <C-/>, but term nvim thinks this is <C-_>
set pastetoggle=<C-_>

" Don't timeout on mappings
set notimeout

" Numbering:
set number

" Window Splitting: Set split settings (options: splitright, splitbelow)
set splitright

" Terminal Color Support: only set guicursor if truecolor
if $COLORTERM ==# 'truecolor'
  set termguicolors
else
  set guicursor=
endif

" Set Background: defaults do dark
set background=dark

" Colorcolumn:
set colorcolumn=80

" Status Line: specifics for custom status line
set laststatus=2
set ttimeoutlen=50
set noshowmode

" ShowCommand: turn off character printing to vim status line
set noshowcmd

" Updatetime: time Vim waits to do something after I stop moving
set updatetime=300

" Linux Dev Path: system libraries
set path+=/usr/include/x86_64-linux-gnu/

" Vim History: for command line; can't imagine that more than 100 is needed
set history=100

augroup custom_incsearch_highlight
  autocmd!
  autocmd CmdlineEnter /,\? set hlsearch
  autocmd CmdlineLeave /,\? set nohlsearch
augroup end

" }}}
```

**Comment by pappasam** [comment] 2020-10-23 17:51
It looks like this line is the culprit: `autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')`. If you get signature help on placeholder jump, this somehow conflicts with snippet expansion. So as you suggested, this is a conflict with `coc-snippets` and `coc.nvim`'s `showSignatureHelp` async action.

**Comment by chemzqm** [comment] 2020-10-23 18:24
I have those settings as well, but works fine

**Comment by pappasam** [comment] 2020-10-23 18:44
Very strange...

**Comment by adworacz** [comment] 2020-10-29 18:06
So I started receiving nvim segaults as well very recently, and I think its rooted in coc-tsserver. I'm not using `coc-pairs`.

I've noticed it with go-to-definition behavior, specifically. It only started happening after I did an update to Coc (via `PlugUpdate`) and then a `CocUpdate`, which I believe brought down a newer version of `coc-tsserver`.

Now I segfault pretty reliably when jumping to definitions, etc.

Not that it helps much, but I see the following after attempting a faulty got-to-definition:
```
sh: segmentation fault nvim
<exit code is 139>
```

**Comment by adworacz** [comment] 2020-10-30 22:16
Got a segfault, with some logging enabled. 

It's not much, but I had to introspect the /tmp/nvim* directories to find the right log. This appears to be the one, and here's the last few lines right before/during the crash:
```
nfo 1690 [15:3:10.522] response:
    {"seq":0,"type":"response","command":"documentHighlights","request_seq":114,"success":true,"body":[{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts","highlightSpans":[{"start":{"line":22,"offset":10},"end":{"line":22,"offset":29},"contextStart":{"line":22,"offset":1},"contextEnd":{"line":22,"offset":72},"kind":"writtenReference"},{"start":{"line":35,"offset":15},"end":{"line":35,"offset":34},"kind":"reference"}]}]}
Info 1691 [15:3:13.719] request:
    {"seq":115,"type":"request","command":"documentHighlights","arguments":{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts"]}}
Perf 1692 [15:3:13.724] 115::documentHighlights: elapsed time (in milliseconds) 4.5544
Info 1693 [15:3:13.724] response:
    {"seq":0,"type":"response","command":"documentHighlights","request_seq":115,"success":true,"body":[{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts","highlightSpans":[{"start":{"line":22,"offset":10},"end":{"line":22,"offset":29},"contextStart":{"line":22,"offset":1},"contextEnd":{"line":22,"offset":72},"kind":"writtenReference"},{"start":{"line":35,"offset":15},"end":{"line":35,"offset":34},"kind":"reference"}]}]}
Info 1694 [15:3:24.677] request:
    {"seq":116,"type":"request","command":"documentHighlights","arguments":{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts"]}}
Perf 1695 [15:3:24.681] 116::documentHighlights: elapsed time (in milliseconds) 3.5798
Info 1696 [15:3:24.681] response:
    {"seq":0,"type":"response","command":"documentHighlights","request_seq":116,"success":true,"body":[{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts","highlightSpans":[{"start":{"line":22,"offset":10},"end":{"line":22,"offset":29},"contextStart":{"line":22,"offset":1},"contextEnd":{"line":22,"offset":72},"kind":"writtenReference"},{"start":{"line":35,"offset":15},"end":{"line":35,"offset":34},"kind":"reference"}]}]}
Info 1697 [15:3:24.882] request:
    {"seq":117,"type":"request","command":"documentHighlights","arguments":{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts"]}}
Perf 1698 [15:3:24.886] 117::documentHighlights: elapsed time (in milliseconds) 3.8901
Info 1699 [15:3:24.886] response:
    {"seq":0,"type":"response","command":"documentHighlights","request_seq":117,"success":true,"body":[{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts","highlightSpans":[{"start":{"line":22,"offset":10},"end":{"line":22,"offset":29},"contextStart":{"line":22,"offset":1},"contextEnd":{"line":22,"offset":72},"kind":"writtenReference"},{"start":{"line":35,"offset":15},"end":{"line":35,"offset":34},"kind":"reference"}]}]}
Info 1700 [15:3:32.192] request:
    {"seq":118,"type":"request","command":"definition","arguments":{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts","line":35,"offset":21}}
Perf 1701 [15:3:32.208] 118::definition: elapsed time (in milliseconds) 16.8955
Info 1702 [15:3:32.209] response:
    {"seq":0,"type":"response","command":"definition","request_seq":118,"success":true,"body":[{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/graphql/plugins/auth-operation.ts","start":{"line":4,"offset":14},"end":{"line":4,"offset":33},"contextStart":{"line":4,"offset":1},"contextEnd":{"line":15,"offset":2}}]}
Info 1703 [15:3:32.217] request:
    {"seq":119,"type":"request","command":"close","arguments":{"file":"//home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts"}}
Info 1704 [15:3:32.220] ConfigFilePresence:: Current Watches: :: File: //home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1705 [15:3:32.221] ConfigFilePresence:: Current Watches: :: File: //home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1706 [15:3:32.221] ConfigFilePresence:: Current Watches: :: File: //home/user/workplace/server/src/serverLambda/src/serverlambda/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1707 [15:3:32.221] ConfigFilePresence:: Current Watches: :: File: //home/user/workplace/server/src/serverLambda/src/serverlambda/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1708 [15:3:32.221] ConfigFilePresence:: Current Watches: :: File: //home/user/workplace/server/src/serverLambda/src/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1709 [15:3:32.221] ConfigFilePresence:: Current Watches: :: File: //home/user/workplace/server/src/serverLambda/src/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1710 [15:3:32.222] ConfigFilePresence:: Current Watches: Config file:: File: //home/user/workplace/server/src/serverLambda/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 1711 [15:3:32.222] FileWatcher:: Added:: WatchInfo: //home/user/workplace/server/src/serverLambda/src/serverlambda/handlers/graphql.factory.ts 500 undefined Project:  WatchType: Closed Script info
Info 1712 [15:3:32.222] Project '//home/user/workplace/server/src/serverLambda/tsconfig.json' (Configured)
Info 1712 [15:3:32.223] 	Files (1590)

Info 1712 [15:3:32.223] -----------------------------------------------
Info 1712 [15:3:32.223] Project '/dev/null/autoImportProviderProject2*' (AutoImportProvider)
Info 1712 [15:3:32.223] 	Files (3)

Info 1712 [15:3:32.223] -----------------------------------------------
Info 1712 [15:3:32.223] Open files: 
Perf 1712 [15:3:32.223] 119::close: async elapsed time (in milliseconds) 6.1224
```

This is making me think this `tsserver` log isn't catching the actual failure, and that I need to enable the language server logging.

**Comment by chemzqm** [comment] 2020-11-02 10:27
Should be something wired with neovim https://github.com/neovim/neovim/wiki/FAQ#debug.

**Comment by adworacz** [comment] 2020-11-11 17:54
Okay, I've attempted to turn on all of the coredump/debugging tools for neovim, lets see if they produce something.

**Comment by chemzqm** [comment] 2020-11-11 18:17
Try upgrade coc.nvim to latest version.

**Comment by adworacz** [comment] 2020-11-13 23:12
Okay, I managed to get a stacktrace from Neovim, but I'm not sure how useful it is without debug symbols, etc. 

Attaching here.
[neovim-segfault-bt.txt](https://github.com/neoclide/coc-tsserver/files/5539692/neovim-segfault-bt.txt)

I'll try upgrading coc.nvim to the latest version as well.

**Comment by adworacz** [comment] 2020-11-25 00:31
Ever since upgrading to the latest coc.nvim version, I haven't encountered the segfault for about a week.

**Comment by chemzqm** [comment] 2020-11-25 03:06
Try upgrade neovim to latest master if you're using neovim 0.5.0.

**Comment by adworacz** [comment] 2020-11-25 19:19
> Try upgrade neovim to latest master if you're using neovim 0.5.0.

I use 0.4.4, which is what was segfaulting before the coc.nvim update that I described above.

**Comment by chemzqm** [comment] 2020-11-26 02:46
@adworacz please provide minimal vimrc and reproduce steps.

**Comment by adworacz** [comment] 2020-11-26 03:13
I think something’s being confused - I am no longer receiving the segfault. 

I upgraded coc.nvim as you suggested 14 days ago, and the segfault never reappeared.

**Comment by chemzqm** [comment] 2020-12-09 06:57
Should be fixed

**Closed by chemzqm** 2020-12-09 06:57 UTC
Labels: Can't reproduce

**Comment by fabriziobertoglio1987** [comment] 2021-02-19 22:24
very experimental software..... :laughing:
