### ISSUE TITLE
How do we rename a directory and have it update all imports?

### ISSUE THREAD

**Issue by geoyws** [neoclide/coc-tsserver#132] opened 2020-03-26 09:07 UTC
Right now I'm doing it via VSCode instead. I've scoured Google and the official docs but found nothing... Thanks for the help!

**Comment by chemzqm** [comment] 2020-03-26 09:18
It can't because coc.nvim only detect file changes for now, duplicate of #52, we need try to find out some solution.

**Comment by geoyws** [comment] 2020-03-26 09:19
Thanks man. Appreciate the effort. Perhaps we could find out how VSCode does it.

**Closed by chemzqm** 2020-03-26 09:18 UTC

**Comment by geoyws** [comment] 2020-03-29 06:14
Maybe we could collaborate with NERDTree and netrw and hook in from their hooks?

**Comment by chemzqm** [comment] 2020-03-30 02:59
> Maybe we could collaborate with NERDTree and netrw and hook in from their hooks? 

Not needs, watchman can watch folder name change.
