### ISSUE TITLE
For some variables names, completion not working?

### ISSUE THREAD

**Issue by zlianon** [neoclide/coc-tsserver#26] opened 2019-05-13 08:43 UTC
![2019-05-13-104140_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/57607686-e8407680-756b-11e9-939f-23042b300d40.png)
![2019-05-13-104202_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/57607687-e8407680-756b-11e9-8d77-37bed9daab1b.png)

**Comment by chemzqm** [comment] 2019-05-13 10:48
Reproduced, it should be bug of tsserver, so just need to wait.

**Comment by chemzqm** [comment] 2019-06-09 07:06
Reproduced with VSCode.

**Comment by zurp** [comment] 2019-11-09 00:21
Same here, but I can't reproduce it in vscode now.

**Comment by chemzqm** [comment] 2020-04-18 09:35
Should be fixed on latest tsserver, can't reproduce anymore.

**Closed by chemzqm** 2020-04-18 09:35 UTC
Labels: bug
